// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mockclient is a generated GoMock package.
package mockclient

import (
	context "context"
	valkey "go-fiber-template/client/valkey"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPingResult is a mock of PingResult interface.
type MockPingResult struct {
	ctrl     *gomock.Controller
	recorder *MockPingResultMockRecorder
}

// MockPingResultMockRecorder is the mock recorder for MockPingResult.
type MockPingResultMockRecorder struct {
	mock *MockPingResult
}

// NewMockPingResult creates a new mock instance.
func NewMockPingResult(ctrl *gomock.Controller) *MockPingResult {
	mock := &MockPingResult{ctrl: ctrl}
	mock.recorder = &MockPingResultMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPingResult) EXPECT() *MockPingResultMockRecorder {
	return m.recorder
}

// Err mocks base method.
func (m *MockPingResult) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockPingResultMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockPingResult)(nil).Err))
}

// MockValkeyClient is a mock of ValkeyClient interface.
type MockValkeyClient struct {
	ctrl     *gomock.Controller
	recorder *MockValkeyClientMockRecorder
}

// MockValkeyClientMockRecorder is the mock recorder for MockValkeyClient.
type MockValkeyClientMockRecorder struct {
	mock *MockValkeyClient
}

// NewMockValkeyClient creates a new mock instance.
func NewMockValkeyClient(ctrl *gomock.Controller) *MockValkeyClient {
	mock := &MockValkeyClient{ctrl: ctrl}
	mock.recorder = &MockValkeyClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValkeyClient) EXPECT() *MockValkeyClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockValkeyClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockValkeyClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockValkeyClient)(nil).Close))
}

// Ping mocks base method.
func (m *MockValkeyClient) Ping(ctx context.Context) valkey.PingResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(valkey.PingResult)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockValkeyClientMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockValkeyClient)(nil).Ping), ctx)
}
