// Code generated by MockGen. DO NOT EDIT.
// Source: go-fiber-template/client/valkey (interfaces: ValkeyClient)

// Package valkey is a generated GoMock package.
package valkey

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockValkeyClient is a mock of ValkeyClient interface.
type MockValkeyClient struct {
	ctrl     *gomock.Controller
	recorder *MockValkeyClientMockRecorder
}

// MockValkeyClientMockRecorder is the mock recorder for MockValkeyClient.
type MockValkeyClientMockRecorder struct {
	mock *MockValkeyClient
}

// NewMockValkeyClient creates a new mock instance.
func NewMockValkeyClient(ctrl *gomock.Controller) *MockValkeyClient {
	mock := &MockValkeyClient{ctrl: ctrl}
	mock.recorder = &MockValkeyClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValkeyClient) EXPECT() *MockValkeyClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockValkeyClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockValkeyClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockValkeyClient)(nil).Close))
}

// Delete mocks base method.
func (m *MockValkeyClient) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockValkeyClientMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockValkeyClient)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockValkeyClient) Get(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockValkeyClientMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockValkeyClient)(nil).Get), arg0)
}

// Set mocks base method.
func (m *MockValkeyClient) Set(arg0, arg1 string, arg2 time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockValkeyClientMockRecorder) Set(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockValkeyClient)(nil).Set), arg0, arg1, arg2)
}
